const audioFileList = [
  {
    id: "a",
    url: "african-bliss-master.mp3",
    title: "track title 1",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "b",
    url: "african-moon-master.mp3",
    title: "track title 2",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "c",
    url: "african-secret-master.mp3",
    title: "track title 3",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "d",
    url: "african-bliss-master.mp3",
    title: "track title 4",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "e",
    url: "african-moon-master.mp3",
    title: "track title 5",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "f",
    url: "african-secret-master.mp3",
    title: "track title 6",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "g",
    url: "african-bliss-master.mp3",
    title: "track title 7",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "h",
    url: "african-moon-master.mp3",
    title: "track title 8",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "i",
    url: "african-secret-master.mp3",
    title: "track title 9",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "j",
    url: "african-bliss-master.mp3",
    title: "track title 10",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "k",
    url: "african-moon-master.mp3",
    title: "track title 11",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "l",
    url: "african-secret-master.mp3",
    title: "track title 12",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
  {
    id: "m",
    url: "african-bliss-master.mp3",
    title: "track title 13",
    imgUrl: "https://source.unsplash.com/collection/1163637/50x50",
  },
];
